name: CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 2 * * 5"

jobs:
  build:
    runs-on: ubuntu-18.04

    env:
      DEBFULLNAME: "Fred Hornsey"
      DEBEMAIL: "hornseyf@objectcomputing.com"

    steps:
    - name: Install Ubuntu Packages
      run: sudo apt-get install debhelper

    - name: Checkout OpenDDS-Debian
      uses: actions/checkout@v2
      with:
        path: OpenDDS-Debian

    - name: Checkout OpenDDS
      uses: actions/checkout@v2
      with: 
        repository: 'objectcomputing/OpenDDS'
        path: OpenDDS

    - name: Copy debian Directory
      run: cp -r OpenDDS-Debian/debian OpenDDS/debian

    - name: Build Package
      run: |
        cd OpenDDS
        dpkg-buildpackage -us -uc
        cd ..
        cp opendds_*.deb opendds.deb

    - name: Upload Results
    - uses: actions/upload-artifact@v1
      with:
        path: 'opendds*'
